/* The exercise library — shared by the app and by tests.html, so a test can
   assert against the same list the app actually ships. */

'use strict';

/* -------------------------------------------------------- exercise library */

const LIBRARY = [
  { name: 'Barbell Back Squat', type: 'lifting', group: 'Legs' },
  { name: 'Front Squat', type: 'lifting', group: 'Legs' },
  { name: 'Romanian Deadlift', type: 'lifting', group: 'Legs' },
  { name: 'Leg Press', type: 'lifting', group: 'Legs' },
  { name: 'Walking Lunge', type: 'lifting', group: 'Legs' },
  { name: 'Goblet Squat', type: 'lifting', group: 'Legs' },
  { name: 'Bodyweight Squat', type: 'lifting', group: 'Legs' },
  { name: 'Dumbbell Lunge', type: 'lifting', group: 'Legs' },
  { name: 'Dumbbell Romanian Deadlift', type: 'lifting', group: 'Legs' },
  { name: 'Glute Bridge', type: 'lifting', group: 'Legs' },
  { name: 'Leg Curl', type: 'lifting', group: 'Legs' },
  { name: 'Calf Raise', type: 'lifting', group: 'Legs' },
  { name: 'Hack Squat', type: 'lifting', group: 'Legs' },
  { name: 'Bulgarian Split Squat', type: 'lifting', group: 'Legs' },
  { name: 'Leg Extension', type: 'lifting', group: 'Legs' },
  { name: 'Seated Leg Curl', type: 'lifting', group: 'Legs' },
  { name: 'Hip Thrust', type: 'lifting', group: 'Legs' },
  { name: 'Sumo Deadlift', type: 'lifting', group: 'Legs' },
  { name: 'Step-Up', type: 'lifting', group: 'Legs' },
  { name: 'Good Morning', type: 'lifting', group: 'Legs' },
  { name: 'Seated Calf Raise', type: 'lifting', group: 'Legs' },
  { name: 'Hip Abduction', type: 'lifting', group: 'Legs' },
  { name: 'Hip Adduction', type: 'lifting', group: 'Legs' },

  { name: 'Barbell Bench Press', type: 'lifting', group: 'Chest' },
  /* The barbell incline was missing while the dumbbell one was here, which is
     the kind of gap that makes somebody give up and type it by hand. */
  { name: 'Incline Barbell Bench Press', type: 'lifting', group: 'Chest' },
  { name: 'Incline Dumbbell Press', type: 'lifting', group: 'Chest' },
  { name: 'Decline Bench Press', type: 'lifting', group: 'Chest' },
  { name: 'Push-Up', type: 'lifting', group: 'Chest' },
  { name: 'Dumbbell Bench Press', type: 'lifting', group: 'Chest' },
  { name: 'Chest Press Machine', type: 'lifting', group: 'Chest' },
  { name: 'Pec Deck', type: 'lifting', group: 'Chest' },
  { name: 'Dumbbell Fly', type: 'lifting', group: 'Chest' },
  { name: 'Chest Dip', type: 'lifting', group: 'Chest' },
  { name: 'Pike Push-Up', type: 'lifting', group: 'Shoulders' },
  { name: 'Cable Fly', type: 'lifting', group: 'Chest' },

  { name: 'Overhead Press', type: 'lifting', group: 'Shoulders' },
  { name: 'Dumbbell Lateral Raise', type: 'lifting', group: 'Shoulders' },
  { name: 'Cable Lateral Raise', type: 'lifting', group: 'Shoulders' },
  { name: 'Face Pull', type: 'lifting', group: 'Shoulders' },
  { name: 'Dumbbell Shoulder Press', type: 'lifting', group: 'Shoulders' },
  { name: 'Machine Shoulder Press', type: 'lifting', group: 'Shoulders' },
  { name: 'Arnold Press', type: 'lifting', group: 'Shoulders' },
  { name: 'Rear Delt Fly', type: 'lifting', group: 'Shoulders' },
  { name: 'Upright Row', type: 'lifting', group: 'Shoulders' },
  { name: 'Barbell Shrug', type: 'lifting', group: 'Shoulders' },

  { name: 'Deadlift', type: 'lifting', group: 'Back' },
  { name: 'Rack Pull', type: 'lifting', group: 'Back' },
  { name: 'Pull-Up', type: 'lifting', group: 'Back' },
  { name: 'Chin-Up', type: 'lifting', group: 'Back' },
  { name: 'Lat Pulldown', type: 'lifting', group: 'Back' },
  { name: 'Barbell Row', type: 'lifting', group: 'Back' },
  { name: 'T-Bar Row', type: 'lifting', group: 'Back' },
  { name: 'Chest-Supported Row', type: 'lifting', group: 'Back' },
  { name: 'Seated Cable Row', type: 'lifting', group: 'Back' },
  { name: 'Dumbbell Row', type: 'lifting', group: 'Back' },
  { name: 'Machine Row', type: 'lifting', group: 'Back' },
  { name: 'Straight-Arm Pulldown', type: 'lifting', group: 'Back' },
  { name: 'Inverted Row', type: 'lifting', group: 'Back' },

  { name: 'Barbell Curl', type: 'lifting', group: 'Arms' },
  { name: 'Dumbbell Curl', type: 'lifting', group: 'Arms' },
  { name: 'Hammer Curl', type: 'lifting', group: 'Arms' },
  { name: 'Preacher Curl', type: 'lifting', group: 'Arms' },
  { name: 'Cable Curl', type: 'lifting', group: 'Arms' },
  { name: 'Triceps Pushdown', type: 'lifting', group: 'Arms' },
  { name: 'Overhead Triceps Extension', type: 'lifting', group: 'Arms' },
  { name: 'Close-Grip Bench Press', type: 'lifting', group: 'Arms' },
  { name: 'Triceps Dip', type: 'lifting', group: 'Arms' },
  { name: 'Skull Crusher', type: 'lifting', group: 'Arms' },
  { name: 'Wrist Curl', type: 'lifting', group: 'Arms' },

  { name: 'Plank', type: 'timed', group: 'Core' },
  { name: 'Side Plank', type: 'timed', group: 'Core' },
  { name: 'Dead Hang', type: 'timed', group: 'Back' },
  { name: 'Wall Sit', type: 'timed', group: 'Legs' },
  { name: 'Hollow Hold', type: 'timed', group: 'Core' },
  { name: 'Hanging Leg Raise', type: 'lifting', group: 'Core' },
  { name: 'Cable Crunch', type: 'lifting', group: 'Core' },
  { name: 'Ab Wheel Rollout', type: 'lifting', group: 'Core' },
  { name: 'Sit-Up', type: 'lifting', group: 'Core' },
  { name: 'Russian Twist', type: 'lifting', group: 'Core' },
  { name: 'Back Extension', type: 'lifting', group: 'Core' },
  { name: 'Run', type: 'cardio', group: 'Cardio' },
  { name: 'Treadmill', type: 'cardio', group: 'Cardio' },
  { name: 'Walk', type: 'cardio', group: 'Cardio' },
  { name: 'Cycling', type: 'cardio', group: 'Cardio' },
  { name: 'Rowing Machine', type: 'cardio', group: 'Cardio' },
  { name: 'Elliptical', type: 'cardio', group: 'Cardio' },
  { name: 'Stair Climber', type: 'cardio', group: 'Cardio' },
  { name: 'Swimming', type: 'cardio', group: 'Cardio' },
  { name: 'Jump Rope', type: 'cardio', group: 'Cardio' },
  /* Incline work is its own entry rather than a field on Treadmill: the whole
     point is that it is a different effort at the same pace, so keeping the
     history separate is what makes the progress chart mean anything. */
  { name: 'Incline Treadmill Walk', type: 'cardio', group: 'Cardio' },
  { name: 'Stationary Bike', type: 'cardio', group: 'Cardio' },
  { name: 'Spin Class', type: 'cardio', group: 'Cardio' },
  { name: 'Hiking', type: 'cardio', group: 'Cardio' },

  /* Measured in minutes and nothing else — no distance, no reps. */
  { name: 'Yoga', type: 'practice', group: 'Practice' },
  { name: 'Vinyasa Yoga', type: 'practice', group: 'Practice' },
  { name: 'Hatha Yoga', type: 'practice', group: 'Practice' },
  { name: 'Hot Yoga', type: 'practice', group: 'Practice' },
  { name: 'Yin Yoga', type: 'practice', group: 'Practice' },
  { name: 'Pilates', type: 'practice', group: 'Practice' },
  { name: 'Mat Pilates', type: 'practice', group: 'Practice' },
  { name: 'Reformer Pilates', type: 'practice', group: 'Practice' },
  { name: 'Barre', type: 'practice', group: 'Practice' },
  { name: 'Stretching', type: 'practice', group: 'Practice' },
  { name: 'Mobility', type: 'practice', group: 'Practice' },
  { name: 'Foam Rolling', type: 'practice', group: 'Practice' },
  { name: 'Tai Chi', type: 'practice', group: 'Practice' },
];
